travis:
  secure:
    BINSTAR_TOKEN: hw3oDqPpDrQJ0IKCSQbdwDHLkQ5QHUIx45WBB23Trm4F7l0DgZus0KBc6Xv93YGsGHUWazvDYxyj7rwrbGuTBjGje1U1V2nxA1TLLE5v1Wv3cfkfwiAQjkgyxvZnRKl2xAYAVnWa5iM/cXjWagmbx5lj/e/iN2jn0b8d+KzueefPCM6wmkTyJpngxeWyqa2mKcwuGiKF8ykHGbZhiCtJF6xWtdnMDSkCHaRg0rrpXxKATa5fHfC65a+zmEDp1dmX4GjJtQbZLr3q+mAf9saWzaFBTb2+PVzemMA7cBCq0cBSMopm5UXxx6v+se/q26A58+jpunr/+kt12zoUi4wY/lr4R5Ufaly0Os4Pgw71EXhgou87PODc4p3iBtFEYk3Ins67ArOGCidolkKQ3ZxmbvXDiJophDALDv7aJHbJfWMNEE04sylxGqqct4xxOBhPQJU0emOoBQCm2PC4dBulAY+SkehPke9JHP3uC4vb4ZWIBd+zPZAkL0MQU0H93G0UxW1CrdO7/iVf4MSP+dVIUs6e9w8PKZD1nAFB3bxpbTbCfYT7xyg3i2idDlpc4OZdGuhmqZy7HQu3WBrH2Q2PJcZqmETXMS7/gmJ7wljEZU/d8kFCGC+7m/YYcP9MWGbJyPsCKpXWqgIF24V36IjbyymQvUhWn07tKA9hw2X6y+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
